examen/pokemon/pokemon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from . import settings
from pokemones.views import PokemonViewSet
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'api', PokemonViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/logout/', LogoutView.as_view(), name="logout"),  # Corrección aquí
    path("accounts/", include("django.contrib.auth.urls")),
    path('', include('pokemones.urls')),
]

urlpatterns += router.urls

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

examen/pokemon/pokemones/urls.py
from django.urls import path

from .views import Listado, Detalle
from . import views

app_name = "pokemones"
urlpatterns = [
    path("", Listado.as_view(), name="index"),
    path("<int:pk>/", Detalle.as_view(), name="detalle"),
]

examen/pokemon/pokemones/models.py
from django.db import models

class Tipo(models.Model):
    nombre = models.CharField(max_length=100)
    imagen = models.ImageField(upload_to='fotos')
    color = models.CharField(max_length=100)  # Campo color

    def __str__(self):
        return self.nombre

class Ataque(models.Model):
    nombre = models.CharField(max_length=100)
    tipo = models.ForeignKey(Tipo, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

class Pokemon(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    tipo = models.ForeignKey(Tipo, on_delete=models.CASCADE)
    ataques = models.ManyToManyField(Ataque)  # Usamos ManyToManyField para relacionar Pokemons y Ataques
    imagen = models.ImageField(upload_to='fotos')

    def __str__(self):
        return self.nombre

examen/pokemon/pokemones/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views import generic
from httplib2 import Response
from .models import Pokemon
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework.authentication import SessionAuthentication, BasicAuthentication, TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.decorators import api_view
from rest_framework import viewsets, status
from rest_framework import generics
# Create your views here.
class Listado(generic.ListView):
    template_name = "pokemones/listado.html"
    model = Pokemon
    paginate_by = 4

class Detalle(LoginRequiredMixin, generic.DetailView):
    template_name = "pokemones/detalle.html"
    model = Pokemon
    authentication_classes = [SessionAuthentication, BasicAuthentication, TokenAuthentication]
    permission_classes = [IsAuthenticated]

from rest_framework import viewsets

from .serializers import PokemonListSerializer, PokemonSerializer, UserSerializer

class PokemonViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Pokemon.objects.all()
    serializer_class = PokemonSerializer
    authentication_classes = [SessionAuthentication, BasicAuthentication, TokenAuthentication]
    permission_classes = [IsAuthenticated]

class PokemonListView(generics.ListAPIView):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Pokemon.objects.all()
    serializer_class = PokemonListSerializer
    authentication_classes = [SessionAuthentication, BasicAuthentication, TokenAuthentication]
    permission_classes = [IsAuthenticated]

@api_view(['POST'])
def register_user(request):
    if request.method == 'POST':
        serializer = UserSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

examen/pokemon/pokemones/templates/pokemones/base.html
<!DOCTYPE html>
<head>
    <title>Pinguinos - 
        {% block titulo %}

        {% endblock titulo %}

    </title>
</head>
<body>
    <a href="{% url 'pokemones:index' %}">Home</a><br>
    {% if user.is_authenticated %}
        {{ user }} 
        <form method="post" action="{% url 'logout' %}">
            {% csrf_token %}
            <button type="submit">logout</button>
        </form>
    {% else %}
    <a href="{% url 'login' %}">Entrar</a>
    {% endif %}
    {% block contenido %}

    {% endblock contenido %}
</body>
</html>

examen/pokemon/pokemones/templates/pokemones/detalle.html
{% extends 'pokemones/base.html' %}

{% block contenido %}

    <h1>{{object.nombre}}</h1>
    <p>{{object.descripcion}}</p>
    <img src="{{object.imagen.url}}">

{% endblock contenido %}

{% block titulo %}
    {{object.nombre}}
{% endblock titulo %}

examen/pokemon/pokemones/templates/pokemones/listado.html
{% extends 'pokemones/base.html' %}

{% block contenido %}

    <ul>
    {% for object in object_list %}
        <li><a href="{% url 'pokemones:detalle' object.id %}">{{object}}</a></li>
    {% endfor %}
    </ul>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock contenido %}

{% block titulo %}
    Listado
{% endblock titulo %}