examen/examen/examen/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("incidencias/", include("incidencias.urls")),
    path("admin/", admin.site.urls),
]

examen/examen/incidencias/urls.py
from django.urls import path
from .views import ListadoLineasView, NuevaIncidenciaView
from . import views

app_name = "incidencias"
urlpatterns = [
    path("", views.index, name="index"),
    path('listado/', ListadoLineasView.as_view(), name='listado'),
    path('nueva_incidencia/<int:estacion_id>/', NuevaIncidenciaView.as_view(), name='nueva_incidencia'),
]

examen/examen/incidencias/models.py
import datetime
from django.db import models

class Linea(models.Model):
    nombre = models.CharField(max_length=200)
    color = models.CharField(max_length=30)
    distancia = models.IntegerField(default=0)

    def __str__(self):
        return self.nombre
    
class Estacion(models.Model):
    nombre = models.CharField(max_length=200)
    linea = models.ForeignKey(Linea, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre
    

class Incidencia(models.Model):
    texto = models.CharField(max_length=200)
    fecha = models.DateTimeField("date published")
    estacion = models.ForeignKey(Estacion, on_delete=models.CASCADE)

    def __str__(self):
        return f"Nombre de la estación({self.estacion}) {self.texto}"

examen/examen/incidencias/views.py
from datetime import datetime
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views import generic
from .models import Linea, Estacion, Incidencia


def index(request):
    return HttpResponse("Hello, world. You're at the incidencias index.")

class ListadoLineasView(generic.ListView):
    model = Estacion
    template_name = 'estacion_list.html'
    context_object_name = 'estaciones'


def enviado_view(request):
    # Renderizar la plantilla con el mensaje de éxito
    mensaje_exito = "La incidencia ha sido enviada."
    return render(request, 'enviado.html', {'mensaje_exito': mensaje_exito})

class NuevaIncidenciaView(generic.CreateView):
    model = Incidencia
    fields = ['texto']
    template_name = 'nueva_incidencia.html'
    success_url = reverse_lazy('enviado')
    
    def form_valid(self, form):
        estacion_id = self.kwargs['estacion_id']
        form.instance.fecha = datetime.now()
        estacion = Estacion.objects.get(pk=estacion_id)
        form.instance.estacion = estacion
        return super().form_valid(form)

examen/examen/incidencias/templates/enviado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Enviado</title>
</head>
<body>
    <h1>{{ mensaje_exito }}</h1>
    <script>
        setTimeout(function() {
            window.location.href = "{% url 'listado' %}";
        }, 2000); // 2000 milisegundos = 2 segundos
    </script>
</body>
</html>

examen/examen/incidencias/templates/incidencias/base.html
<!DOCTYPE html>
<head>
    <title>Metro - 
        {% block titulo %}

        {% endblock titulo %}

    </title>
</head>
<body>
    {% block contenido %}

    {% endblock contenido %}
</body>
</html>

examen/examen/incidencias/templates/incidencias/estacion_list.html
{% extends 'incidencias/base.html' %}

{% block contenido %}
<h1>Listado de Líneas de Metro</h1>
<ul>
    {% for estacion in estaciones %}
        <li>{{ estacion.linea.nombre }} - {{ estacion.nombre }} 
            <a href="{% url 'incidencias:nueva_incidencia' estacion_id=estacion.id %}">Nueva incidencia</a>
        </li>
    {% endfor %}
</ul>
{% endblock contenido %}

{% block titulo %}
    Listado
{% endblock titulo %}

examen/examen/incidencias/templates/incidencias/nueva_incidencia.html
{% extends 'incidencias/base.html' %}

{% block contenido %}

<h1>Formulario de Incidencia</h1>
<form method="post">
    {{ form.as_p }}
    <button type="submit">Guardar Incidencia</button>
</form>
{% endblock contenido %}

{% block titulo %}
    Incidencia
{% endblock titulo %}

examen/examen/incidencias/templates/nueva_incidencia.html
{% extends 'incidencias/base.html' %}

{% block contenido %}

<h1>Formulario de Incidencia</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar Incidencia</button>
</form>
{% endblock contenido %}

{% block titulo %}
    Incidencia
{% endblock titulo %}